### ISSUE TITLE
现在两张图片都能占坑了吗？😂

### ISSUE THREAD

**Issue by SupritYoung** [michael-wzhu/Chinese-LlaMA2#1]

**Comment by michael-wzhu** [comment]
其他项目也是这么干的 ，比如 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2

**Comment by ymcui** [comment]
> 其他项目也是这么干的 ，比如 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2

@michael-wzhu  大可不必提及我们 😂

**Comment by Tramac** [comment]
就这么卷？

**Comment by michael-wzhu** [comment]
还有这个：https://github.com/yangjianxin1/Firefly-LLaMA2-Chinese
