### ISSUE TITLE
sft配置

### ISSUE THREAD

**Issue by lucasjinreal** [michael-wzhu/Chinese-LlaMA2#11]
楼主可以介绍一下sft相关配置吗，GPU，lr 等，v100上看起来fp16会overflow

**Comment by michael-wzhu** [comment]
V100如果不用zero等手段的确会oom的，配置请参看 [run_train_sft.sh](https://github.com/michael-wzhu/Chinese-LlaMA2/blob/main/src/sft/run_train_sft.sh)。主要是：
- 微调lm head, embedding, 和 rank=20的lora参数
- zero2 + bf16训练，4卡A100-40G

**Comment by lucasjinreal** [comment]
@michael-wzhu v100 还有40G吗

**Comment by michael-wzhu** [comment]
v100应该有32G或者16G的应该

**Comment by lucasjinreal** [comment]
V100 没法训，fp16总是会overflow

**Comment by michael-wzhu** [comment]
要多张v100卡，或者不微调lm head, embedding；加上zero-3，cpu offload,
