### ISSUE TITLE
Readme Error: vvlm-serving-README 链接失效

### ISSUE THREAD

**Issue by hsiong** [michael-wzhu/Chinese-LlaMA2#13]
**Describe the bug**
在 model serving - vvml 部署, 操作步骤参考链接失效, 点击后404

失效链接:   
https://github.com/michael-wzhu/Chinese-LlaMA2/blob/main/src/vllm_serving/REAME.md

**Screenshots**
<img width="816" alt="Screenshot 2023-07-31 at 16 47 53" src="https://github.com/michael-wzhu/Chinese-LlaMA2/assets/37357447/217da1fb-c4c7-4b8f-adf9-03dec2e3ae82">

<img width="1130" alt="Screenshot 2023-07-31 at 16 47 32" src="https://github.com/michael-wzhu/Chinese-LlaMA2/assets/37357447/1029ef70-4474-47cc-a0ae-2c6d59a0b664">

**Expected behavior** 
查看 model serving - vvml 部署的操作步骤

**Comment by michael-wzhu** [comment]
thanks for the feedback. The link is now updated!
