### ISSUE TITLE
二维码过期

### ISSUE THREAD

**Issue by songzijiang** [michael-wzhu/Chinese-LlaMA2#14]
居然在github蹲到校友，readme中的qr过期了，求更新。
顺带求个好友位，一起讨论ai技术

**Comment by tcexeexe** [comment]
> 居然在github蹲到校友，readme中的qr过期了，求更新。 顺带求个好友位，一起讨论ai技术

求拉+1

**Comment by michael-wzhu** [comment]
二维码已更新
